name: Test this action
on:
  push:
    branches-ignore:
    - master
    - v1
    tags-ignore:
    - '*'
    paths-ignore:
    - README.md
jobs:
  common:
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-16.04, ubuntu-18.04, macos-latest, windows-latest ]
        # Use various version syntaxes here for testing
        ruby: [ .ruby-version, .tool-versions, 2.2, 2.3, ruby-head, jruby, jruby-head, truffleruby, truffleruby-head ]
        exclude:
        - os: windows-latest
          ruby: truffleruby
        - os: windows-latest
          ruby: truffleruby-head
    name: ${{ matrix.os }} ${{ matrix.ruby }}
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: ruby version and gcc
      run: |
        ruby --version
        ruby -e "puts 'build gcc: ' + RbConfig::CONFIG.fetch('CC_VERSION_MESSAGE', 'unknown')[/[^\n]+/]"      
    - name: ridk version (mingw)
      if: matrix.os == 'windows-latest'
      run: |
        # run 'ridk version'
        $abi, $plat = $(ruby -e "STDOUT.write RbConfig::CONFIG['ruby_version'] + ' ' + RUBY_PLATFORM").split(' ')
        if (($abi -ge '2.4') -and $plat.Contains('mingw')) {
          ridk version
        } else {
          echo 'ridk is unavailable'
        }
    - name: Subprocess test
      run: ruby test_subprocess.rb
    - name: OpenSSL version
      run: ruby -ropenssl -e 'puts OpenSSL::OPENSSL_LIBRARY_VERSION'
    - name: OpenSSL test
      run: ruby -ropen-uri -e 'puts open(%{https://rubygems.org/}) { |f| f.read(1024) }'
    - name: C extension test
      run: gem install json:2.2.0 --no-document
    - run: bundle --version
    - run: bundle install
    - run: bundle exec rake --version

  specials:
    strategy:
      fail-fast: false
      matrix:
        cfg:
          - { ruby: rubinius, os: ubuntu-18.04   }
          - { ruby: mingw   , os: windows-latest }
          - { ruby: mswin   , os: windows-latest }
    name: ${{ matrix.cfg.os }} ${{ matrix.cfg.ruby }}
    runs-on: ${{ matrix.cfg.os }}
    steps:
    - uses: actions/checkout@v2
    - uses: ./
      with:
        ruby-version: ${{ matrix.cfg.ruby }}
    - name: ruby version and gcc
      run: |
        ruby --version
        ruby -e "puts 'build gcc: ' + RbConfig::CONFIG.fetch('CC_VERSION_MESSAGE', 'unknown')[/[^\n]+/]"      
    - name: ridk version (mingw)
      if: matrix.cfg.os == 'windows-latest'
      run: |
        # run 'ridk version'
        $abi, $plat = $(ruby -e "STDOUT.write RbConfig::CONFIG['ruby_version'] + ' ' + RUBY_PLATFORM").split(' ')
        if (($abi -ge '2.4') -and $plat.Contains('mingw')) {
          ridk version
        } else {
          echo 'ridk is unavailable'
        }
    - name: Subprocess test
      run: ruby test_subprocess.rb
    - name: OpenSSL version
      run: ruby -ropenssl -e 'puts OpenSSL::OPENSSL_LIBRARY_VERSION'
    - name: OpenSSL test
      run: ruby -ropen-uri -e 'puts open(%{https://rubygems.org/}) { |f| f.read(1024) }'
    - name: C extension test
      if: endsWith(matrix.cfg.ruby, 'mswin') == false
      run: gem install json:2.2.0 --no-document
    - name: C extension test (mswin cmd)
      if: endsWith(matrix.cfg.ruby, 'mswin')
      shell: cmd
      run: |
        call %VCVARS%
        gem install json:2.2.0 --no-document
    - name: C extension test (mswin ps1)
      if: endsWith(matrix.cfg.ruby, 'mswin')
      run: |
        cmd.exe /c "$env:VCVARS && set" | Foreach-Object {
          $p, $v = $_.split('=')
          Set-Item -path env:$p -value $v
        }
        gem install json:2.2.0 --no-document
    - run: bundle --version
    - run: bundle install
    - run: bundle exec rake --version

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: yarn install
    - run: yarn run lint
